@extends('layouts.app', ['portal' => 'teacher', 'title' => 'Assignments', 'pageHeading' => 'Assignments & Quizzes'])
@section('content')
@php $assignmentRoutes = ($preview ?? true) ? 'dev.preview.teacher.assignments' : 'teacher.assignments'; @endphp
<div class="page-intro"><div><span class="eyebrow">Teacher portal · Prototype</span><h1>Assignments</h1><p>Organize classroom activities, deadlines, submissions, and grading previews.</p></div><a class="button button-primary" href="{{ route($assignmentRoutes.'.create') }}">+ Create Assignment</a></div>
<div class="prototype-note"><strong>Demonstration data</strong><span>Assignment changes are temporary and are not published to real students.</span></div>
<div class="assignment-toolbar"><label>Search assignments<input type="search" placeholder="Search title or classroom" data-assignment-search></label><label>Status<select data-assignment-status><option value="all">All</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="closed">Closed</option></select></label></div>
<div class="assignment-groups" data-assignment-list>
@foreach (['IT 101 · BSIT 1A'=>[['digital-literacy-reflection','Digital Literacy Reflection','published','Sep 24, 2026 · 8:00 AM','Sep 30, 2026 · 11:59 PM',100,28,12],['hardware-identification','Hardware Identification','scheduled','Oct 1, 2026 · 8:00 AM','Oct 7, 2026 · 5:00 PM',50,0,0]],'CC 102 · BSIT 1B'=>[['programming-lab-04','Programming Lab 04','draft','Not scheduled','Oct 10, 2026 · 5:00 PM',100,0,0],['quiz-03','Quiz 03: Control Structures','closed','Sep 10, 2026 · 8:00 AM','Sep 18, 2026 · 5:00 PM',40,30,3]]] as $classroom => $assignments)
<section class="assignment-group"><h2>{{ $classroom }}</h2><div class="assignment-card-grid">@foreach ($assignments as $assignment)<article class="assignment-card" data-assignment-card data-status="{{ $assignment[2] }}" data-search="{{ strtolower($assignment[1].' '.$classroom) }}"><header><span class="status-chip status-{{ $assignment[2] }}">{{ ucfirst($assignment[2]) }}</span><span>{{ $assignment[5] }} points</span></header><h3>{{ $assignment[1] }}</h3><dl><div><dt>Available</dt><dd>{{ $assignment[3] }}</dd></div><div><dt>Deadline</dt><dd>{{ $assignment[4] }}</dd></div><div><dt>Submissions</dt><dd>{{ $assignment[6] }}</dd></div><div><dt>Awaiting grading</dt><dd>{{ $assignment[7] }}</dd></div></dl><div class="card-actions"><a class="button button-secondary" href="{{ route($assignmentRoutes.'.show', $assignment[0]) }}">View Assignment</a>@if ($assignment[6] > 0)<a class="button button-primary" href="{{ route($assignmentRoutes.'.submissions', $assignment[0]) }}">Submissions</a>@endif</div></article>@endforeach</div></section>
@endforeach
<p class="empty-filter" data-assignment-empty hidden>No assignments match the selected filters.</p></div>
@endsection
