@extends('layouts.app', ['portal' => 'student', 'title' => 'My Classrooms', 'pageHeading' => 'My Classrooms'])
@section('content')
<div class="page-intro"><div><span class="eyebrow">Student portal · First semester</span><h1>My Classrooms</h1><p>View approved classrooms and track your joining requests.</p></div><a class="button button-primary" href="{{ route(($preview ?? true) ? 'dev.preview.student.join' : 'student.classrooms.join') }}">+ Join Classroom</a></div>
@if (! ($preview ?? true))
@foreach (['approved' => 'Approved classrooms', 'pending' => 'Pending joining requests', 'declined' => 'Declined requests'] as $status => $heading)<section class="enrollment-section"><div class="section-heading"><h2>{{ $heading }}</h2></div><div class="classroom-grid">@forelse ($enrollments->where('status', $status) as $enrollment)<article class="classroom-card"><span class="status-chip status-{{ $status }}">{{ ucfirst($status) }}</span><span class="eyebrow">{{ $enrollment->classroom->subject_code }}</span><h2>{{ $enrollment->classroom->subject_name }}</h2><p>{{ $enrollment->classroom->section }} · {{ $enrollment->classroom->teacher->name }}</p><p>{{ $enrollment->classroom->semester }} · AY {{ $enrollment->classroom->academic_year }}</p>@if ($status === 'approved')<a class="button button-primary button-full" href="{{ route('student.classrooms.show', $enrollment->classroom) }}">Enter Classroom</a>@elseif ($status === 'pending')<strong>Waiting for Teacher Approval</strong>@else<span>No classroom access</span>@endif</article>@empty<p class="empty-filter">No {{ strtolower($heading) }}.</p>@endforelse</div></section>@endforeach
@else
<section class="enrollment-section"><div class="section-heading"><h2>Approved classrooms</h2><span>2 classrooms</span></div><div class="classroom-grid">
@foreach ([['slug'=>'introduction-to-it','name'=>'Introduction to Information Technology','code'=>'IT 101','section'=>'BSIT 1A','teacher'=>'Prof. Mira Santos'],['slug'=>'purposive-communication','name'=>'Purposive Communication','code'=>'GEC 105','section'=>'BSIT 1A','teacher'=>'Prof. Leah Ramos']] as $classroom)
<article class="classroom-card"><span class="status-chip status-approved">Approved</span><span class="eyebrow">{{ $classroom['code'] }}</span><h2>{{ $classroom['name'] }}</h2><p>{{ $classroom['section'] }} · {{ $classroom['teacher'] }}</p><p>First semester · AY 2026–2027</p><a class="button button-primary button-full" href="{{ route('dev.preview.student.classroom', $classroom['slug']) }}">Enter Classroom</a></article>
@endforeach</div></section>
<section class="enrollment-section"><div class="section-heading"><h2>Pending joining requests</h2></div><article class="request-card"><div><span class="status-chip status-pending">Pending approval</span><h3>Computer Programming 1</h3><p>CC 102 · BSIT 1B · Requested September 22, 2026</p></div><strong>Waiting for Teacher Approval</strong></article></section>
<section class="enrollment-section"><div class="section-heading"><h2>Declined requests</h2></div><article class="request-card is-muted"><div><span class="status-chip status-declined">Declined</span><h3>Data Structures</h3><p>IT 203 · Section mismatch · September 15, 2026</p></div><span>No classroom access</span></article></section>
@endif
@endsection
