@extends('layouts.app', ['portal' => 'student', 'title' => 'Join Classroom', 'pageHeading' => 'Join Classroom'])
@section('content')
<div class="page-intro"><div><span class="eyebrow">Student portal{{ ($preview ?? true) ? ' · Prototype' : '' }}</span><h1>Join a classroom</h1><p>Enter the joining code shared by your teacher.</p></div><a class="button button-secondary" href="{{ route(($preview ?? true) ? 'dev.preview.student.classrooms' : 'student.classrooms') }}">My Classrooms</a></div>
@if ($preview ?? true)
<div class="prototype-note"><strong>Demonstration only</strong><span>Try sample code <code>CCIT-2026</code>. A matching code creates a pending request and never grants access automatically.</span></div>
<div class="join-layout"><form class="content-panel join-form" data-join-form><label for="class-code">Classroom joining code</label><div class="join-input-row"><input id="class-code" name="class_code" autocomplete="off" required placeholder="Enter joining code"><button class="button button-primary" type="submit">Find Classroom</button></div><p class="form-message" data-join-message aria-live="polite"></p></form>
<article class="classroom-card" data-join-match hidden><span class="status-chip status-pending">Match found</span><span class="eyebrow">IT 101</span><h2>Introduction to Information Technology</h2><p>BSIT 1A · Prof. Mira Santos</p><p>First semester · AY 2026–2027</p><button class="button button-primary button-full" type="button" data-confirm-join>Request to Join</button><div class="pending-confirmation" data-pending-confirmation hidden><strong>Pending Approval</strong><p>Your demonstration request was sent. Classroom access remains locked until teacher approval.</p></div></article></div>
@else
<div class="join-layout"><form class="content-panel join-form" method="GET" action="{{ route('student.classrooms.join') }}"><label for="class-code">Classroom joining code</label><div class="join-input-row"><input id="class-code" name="code" value="{{ request('code') }}" autocomplete="off" required><button class="button button-primary" type="submit">Find Classroom</button></div>@if (request()->filled('code') && ! $classroom)<p class="form-message is-error">No classroom matches that joining code.</p>@endif</form>@if ($classroom)<article class="classroom-card"><span class="status-chip status-pending">Match found</span><span class="eyebrow">{{ $classroom->subject_code }}</span><h2>{{ $classroom->subject_name }}</h2><p>{{ $classroom->section }} · {{ $classroom->teacher->name }}</p><p>{{ $classroom->semester }} · AY {{ $classroom->academic_year }}</p><form method="POST" action="{{ route('student.classrooms.enroll', $classroom) }}">@csrf<button class="button button-primary button-full" type="submit">Request to Join</button></form></article>@endif</div>
@endif
@endsection
