@extends('layouts.app', ['portal' => $portal, 'title' => 'Messages', 'pageHeading' => $portal === 'teacher' ? 'Student Inquiries' : 'Messages'])
@section('content')
<div class="page-intro"><div><span class="eyebrow">{{ ucfirst($portal) }} portal · Prototype</span><h1>{{ $portal === 'teacher' ? 'Student Inquiries' : 'Messages' }}</h1><p>{{ $portal === 'teacher' ? 'Reply to fictional students enrolled in your classrooms.' : 'Message teachers from your approved classrooms.' }}</p></div></div>
<div class="prototype-note"><strong>Private messaging demonstration</strong><span>Messages remain in this browser session and are not delivered to another account or saved permanently.</span></div>
<section class="messaging-shell" data-messaging data-portal="{{ $portal }}">
<aside class="conversation-list" data-conversation-list><header><h2>Conversations</h2><span class="unread-badge">2 unread</span></header>
@php
$conversations = $portal === 'teacher'
    ? [['id'=>'jamie','initials'=>'JF','name'=>'Jamie Flores','subject'=>'IT 101 · BSIT 1A','preview'=>'Thank you, Professor.','unread'=>'2'],['id'=>'patricia','initials'=>'PL','name'=>'Patricia Lim','subject'=>'CC 102 · BSIT 1B','preview'=>'Can I clarify the activity?','unread'=>null]]
    : [['id'=>'mira','initials'=>'MS','name'=>'Prof. Mira Santos','subject'=>'IT 101 · Introduction to IT','preview'=>'Please review Module 2.','unread'=>'2'],['id'=>'leah','initials'=>'LR','name'=>'Prof. Leah Ramos','subject'=>'GEC 105 · Purposive Communication','preview'=>'Your outline looks good.','unread'=>null]];
@endphp
@foreach ($conversations as $index => $conversation)<button class="conversation-item @if ($index === 0) is-active @endif" type="button" data-conversation="{{ $conversation['id'] }}"><span class="avatar">{{ $conversation['initials'] }}</span><span><strong>{{ $conversation['name'] }}</strong><small>{{ $conversation['subject'] }}</small><em>{{ $conversation['preview'] }}</em></span>@if ($conversation['unread'])<b>{{ $conversation['unread'] }}</b>@endif</button>@endforeach
</aside>
<div class="message-panel" data-message-panel><header><button class="message-back" type="button" data-message-back>← Back to Messages</button><div><h2 data-message-name>{{ $conversations[0]['name'] }}</h2><p data-message-subject>{{ $conversations[0]['subject'] }}</p></div></header><div class="message-history" data-message-history><div class="message-date">Today</div><div class="message-bubble is-received"><p>{{ $portal === 'teacher' ? 'Good afternoon, Professor. May I clarify the Module 2 worksheet?' : 'Hello Alex. Please review Module 2 before Wednesday.' }}</p><span>{{ $portal === 'teacher' ? 'Jamie' : 'Prof. Santos' }} · 9:12 AM</span></div><div class="message-bubble is-sent"><p>{{ $portal === 'teacher' ? 'Of course. Which part would you like me to explain?' : 'Thank you, Professor. I will review it today.' }}</p><span>You · 9:18 AM</span></div></div><form class="message-composer" data-message-form><label class="visually-hidden" for="message-body">Message</label><textarea id="message-body" name="message" required placeholder="Write a demonstration message…"></textarea><button class="button button-primary" type="submit">Send</button><p data-message-feedback aria-live="polite"></p></form></div>
<div class="message-empty" data-message-empty hidden><span>✉</span><h2>Select a conversation</h2><p>Choose an approved classroom contact to view demonstration messages.</p></div>
</section>
<section class="permission-note"><h2>Future backend permission requirements</h2><ul><li>Only authenticated students with approved classroom membership may initiate conversations with their classroom teachers.</li><li>Teachers may message only students enrolled in classrooms they own.</li><li>Only authorized conversation participants may read or send messages; students cannot access another student's conversation or impersonate a sender.</li><li>Institutional moderation or safeguarding access requires explicit authorization and a documented policy.</li></ul></section>
@endsection
