@extends('layouts.app', ['portal' => 'teacher', 'title' => 'Create Classroom', 'pageHeading' => 'Create Classroom'])
@section('content')
<div class="page-intro"><div><span class="eyebrow">Teacher portal{{ ($preview ?? true) ? ' · Prototype' : '' }}</span><h1>Create a classroom</h1><p>{{ ($preview ?? true) ? 'Preview a new subject classroom and its demonstration joining code.' : 'Create a persistent classroom and generate a secure joining code.' }}</p></div><a class="button button-secondary" href="{{ route(($preview ?? true) ? 'dev.preview.teacher.classrooms' : 'teacher.classrooms') }}">Back to classrooms</a></div>
@if ($preview ?? true)
<div class="prototype-note"><strong>Prototype form</strong><span>Submitting this form creates a browser-only preview. Nothing is saved permanently.</span></div>
<div class="form-preview-grid">
<form class="content-panel prototype-form" data-classroom-form>
<div class="form-grid"><label>Subject name<input name="subject_name" required placeholder="e.g. Web Development"></label><label>Subject code<input name="subject_code" required placeholder="e.g. IT 204"></label><label class="form-span">Subject description<textarea name="subject_description" required placeholder="A short description of the subject"></textarea></label><label>Section<input name="section" required placeholder="e.g. BSIT 2A"></label><label>Academic year<input name="academic_year" required value="2026–2027"></label><label>Semester<select name="semester" required><option>First semester</option><option>Second semester</option><option>Summer</option></select></label><label>Class schedule<input name="schedule" required placeholder="Tue/Thu · 10:30 AM"></label><label class="form-span">Classroom description<textarea name="classroom_description" required placeholder="Welcome message or classroom expectations"></textarea></label></div><button class="button button-primary button-full" type="submit">Create Prototype Preview</button>
</form>
<aside class="classroom-card preview-card" data-classroom-preview hidden><span class="status-chip status-approved">Prototype preview</span><span class="eyebrow" data-preview-code>SUBJECT CODE</span><h2 data-preview-name>New classroom</h2><p data-preview-meta>Section · Semester · Academic year</p><p data-preview-description></p><div class="join-code"><span>Demonstration joining code</span><strong data-preview-join>DEMO-0000</strong><button type="button" data-copy-preview>Copy</button></div><p class="prototype-caption">This classroom and code have not been saved permanently.</p></aside>
</div>
@else
<form class="content-panel prototype-form" method="POST" action="{{ route('teacher.classrooms.store') }}">@csrf<div class="form-grid"><label>Subject name<input name="subject_name" value="{{ old('subject_name') }}" required></label><label>Subject code<input name="subject_code" value="{{ old('subject_code') }}" required></label><label class="form-span">Subject description<textarea name="subject_description" required>{{ old('subject_description') }}</textarea></label><label>Section<input name="section" value="{{ old('section') }}" required></label><label>Academic year<input name="academic_year" value="{{ old('academic_year', '2026–2027') }}" required></label><label>Semester<select name="semester" required><option>First semester</option><option>Second semester</option><option>Summer</option></select></label><label>Class schedule<input name="class_schedule" value="{{ old('class_schedule') }}" required></label><label class="form-span">Classroom description<textarea name="description" required>{{ old('description') }}</textarea></label></div><button class="button button-primary button-full" type="submit">Create Classroom</button></form>
@endif
@endsection
