@extends('layouts.app', ['portal' => $portal, 'title' => 'Introduction to IT', 'pageHeading' => 'Classroom'])
@section('content')
@php
$isPreview = $preview ?? true;
$subjectCode = isset($classroom) ? $classroom->subject_code : 'IT 101';
$subjectName = isset($classroom) ? $classroom->subject_name : 'Introduction to Information Technology';
$section = isset($classroom) ? $classroom->section : 'BSIT 1A';
$teacherName = isset($classroom) ? $classroom->teacher->name : 'Prof. Mira Santos';
$semester = isset($classroom) ? $classroom->semester : 'First semester';
$academicYear = isset($classroom) ? $classroom->academic_year : '2026–2027';
@endphp
<header class="classroom-hero"><div><span class="eyebrow">{{ $subjectCode }} · {{ $section }}</span><h1>{{ $subjectName }}</h1><p>{{ $teacherName }} · {{ $semester }} · Academic year {{ $academicYear }}</p></div><div class="classroom-hero-actions"><span class="status-chip status-approved">{{ $portal === 'teacher' ? 'Teacher view' : 'Enrolled' }}</span><a class="button button-secondary" href="{{ route($isPreview ? 'dev.preview.'.$portal.'.messages' : $portal.'.messages') }}">{{ $portal === 'teacher' ? 'Student Inquiries' : 'Message Teacher' }}</a></div></header>
<nav class="classroom-tabs" aria-label="Classroom sections">
@foreach (['stream'=>'Stream','modules'=>'Modules','assignments'=>'Assignments','exams'=>'Exams','attendance'=>'Attendance','people'=>'People'] as $key => $label)<button type="button" data-classroom-tab="{{ $key }}" @if ($key === 'stream') class="is-active" aria-selected="true" @else aria-selected="false" @endif>{{ $label }}</button>@endforeach
</nav>
<div class="classroom-tab-panel" data-classroom-panel="stream" data-discussion-stream data-portal="{{ $portal }}">
<div class="stream-layout"><div>
<form class="post-composer" data-post-form><div class="post-composer-heading"><div class="avatar">{{ $portal === 'teacher' ? 'MS' : 'AR' }}</div><div><strong>{{ $portal === 'teacher' ? 'Share with your classroom' : 'Create a classroom post' }}</strong><p>Prototype posts stay in this browser session.</p></div></div><label class="visually-hidden" for="post-content">Post content</label><textarea id="post-content" name="content" maxlength="1200" placeholder="Share a question, idea, or class update…" required></textarea><div class="post-composer-footer"><label class="attachment-placeholder"><input type="file" disabled>＋ Attachment <small>Coming Soon</small></label>@if ($portal === 'teacher')<label class="announcement-toggle"><input type="checkbox" name="announcement"> Official announcement</label>@endif<button class="button button-primary" type="submit">Post to Class</button></div><p class="form-message" data-post-feedback aria-live="polite"></p></form>
<div class="discussion-feed" data-post-feed>
<article class="discussion-post teacher-announcement" data-post-id="official-welcome"><header><div class="avatar">MS</div><div><strong>Prof. Mira Santos</strong><span>Teacher · Today, 8:30 AM</span></div><span class="announcement-label">Official announcement</span></header><p>Welcome to IT 101. Please review Module 2 before Wednesday and bring your questions to class.</p><footer><span data-comment-count>2 comments</span><button type="button" data-toggle-comments>Reply</button>@if ($portal === 'teacher')<button type="button" data-moderate-post>Moderate</button>@endif</footer><div class="post-comments" data-comments hidden><div class="comment"><strong>Jamie Flores</strong><p>Thank you, Professor. Is the worksheet also due Wednesday?</p></div><div class="comment"><strong>Prof. Mira Santos</strong><p>The worksheet is due Friday.</p></div><form data-comment-form><input name="comment" required placeholder="Write a reply…"><button type="submit">Reply</button></form></div></article>
<article class="discussion-post" data-post-id="student-question"><header><div class="avatar">JF</div><div><strong>Jamie Flores</strong><span>Student · Yesterday, 4:12 PM</span></div></header><p>Does anyone have a good way to remember the differences between RAM and storage?</p><footer><span data-comment-count>1 comment</span><button type="button" data-toggle-comments>Reply</button>@if ($portal === 'teacher')<button type="button" data-moderate-post>Moderate</button>@endif</footer><div class="post-comments" data-comments hidden><div class="comment"><strong>Alex Rivera</strong><p>I think of RAM as your desk and storage as your filing cabinet.</p></div><form data-comment-form><input name="comment" required placeholder="Write a reply…"><button type="submit">Reply</button></form></div></article>
</div></div><aside class="stream-sidebar"><div class="content-panel"><span class="eyebrow">Classroom conduct</span><h2>Discussion guidelines</h2><p>Keep posts related to the subject, communicate respectfully, and protect personal information.</p></div><div class="content-panel"><span class="eyebrow">Prototype access</span><p>Posting represents an approved classroom member. Future access must be verified by the server.</p></div></aside></div>
</div>
<div class="classroom-tab-panel" data-classroom-panel="modules" hidden><div class="resource-grid">@foreach ([['Module 1','Digital Citizenship','Reading · Completed'],['Module 2','Computer Hardware Fundamentals','Video and worksheet · In progress'],['Module 3','Operating Systems','Coming Soon']] as $item)<article class="resource-card"><span class="eyebrow">{{ $item[0] }}</span><h3>{{ $item[1] }}</h3><p>{{ $item[2] }}</p></article>@endforeach</div></div>
<div class="classroom-tab-panel" data-classroom-panel="assignments" hidden>@if ($portal === 'teacher')<div class="tab-actions"><div><span class="eyebrow">{{ $subjectCode }} assignments</span><h2>Manage classroom assignments</h2></div><a class="button button-primary" href="{{ route($isPreview ? 'dev.preview.teacher.assignments.create' : 'teacher.assignments.create') }}">+ Create Assignment</a></div>@endif<div class="resource-grid"><article class="resource-card"><span class="status-chip status-pending">Due Sep 30</span><h3>Digital Literacy Reflection</h3><p>Write a 500-word reflection about responsible technology use.</p><strong>{{ $portal === 'student' ? 'Not submitted' : '28 submissions · 12 awaiting grading' }}</strong>@if ($portal === 'teacher')<div class="card-actions"><a class="button button-secondary" href="{{ route($isPreview ? 'dev.preview.teacher.assignments.show' : 'teacher.assignments.show', 'digital-literacy-reflection') }}">Open Assignment</a><a class="button button-primary" href="{{ route($isPreview ? 'dev.preview.teacher.assignments.submissions' : 'teacher.assignments.submissions', 'digital-literacy-reflection') }}">Review Submissions</a></div>@endif</article><article class="resource-card"><span class="status-chip status-approved">Due Oct 7</span><h3>Hardware Identification</h3><p>Label the major components of a computer system.</p><strong>{{ $portal === 'student' ? 'Submitted' : 'Scheduled · 50 points' }}</strong>@if ($portal === 'teacher')<div class="card-actions"><a class="button button-secondary" href="{{ route($isPreview ? 'dev.preview.teacher.assignments.show' : 'teacher.assignments.show', 'hardware-identification') }}">Open Assignment</a></div>@endif</article></div></div>
<div class="classroom-tab-panel" data-classroom-panel="exams" hidden><div class="coming-soon"><span>Exams</span><h2>Midterm examination</h2><p>Scheduled October 14, 2026 · Availability controls are Coming Soon.</p></div></div>
<div class="classroom-tab-panel" data-classroom-panel="attendance" hidden><div class="coming-soon"><span>Attendance</span><h2>Manual attendance and temporary codes</h2><p>This interface is prepared for a future attendance workflow. Coming Soon.</p></div></div>
<div class="classroom-tab-panel" data-classroom-panel="people" hidden><div class="resource-grid"><article class="resource-card"><span class="eyebrow">Instructor</span><h3>Prof. Mira Santos</h3><p>Classroom owner · Active</p></article><article class="resource-card"><span class="eyebrow">Students</span><h3>34 approved members</h3><p>2 requests pending teacher approval</p></article></div></div>
@endsection
